# Generated by Django 5.2.1 on 2025-05-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcrud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=70)),
                ('description', models.CharField()),
                ('TIme', models.TimeField()),
                ('iscomplete', models.BooleanField()),
            ],
        ),
    ]
