# Generated by Django 5.2.1 on 2025-05-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcrud', '0002_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='iscomplete',
            field=models.BooleanField(default=False),
        ),
    ]
